-- @description Paste NPCTalkDialogueTextAudio from Config Editor with Character Filters
-- @author ewan
-- @version 2

-- @about
--   Copy the first seven columns from config and paste them into reaper.

--HOW TO:
-- COPY the first SEVEN columns in config for the steps you want to paste.
-- Then, run this action at the point in the reaper session you wish to insert them.
-- Enter the number of seconds you want to separate each line.
-- IF NPC is the only selected option, all of those NPCs lines will be imported.
-- However, if any number of players are selected, only the NPC responses they would be able to hear are imported.

dialoguePath = [[D:\SVN\4.0.0\bin\Client\Audio\Dialogue\]]
-- Paste your dialogue path above, if not the same as mine. 

-- The colour used is chosen at random, and is guaranteed to not be the same as the preceeding region.
-- On the below line is where you can define your colour scheme with hex codes.
colourscheme = {"#FFBE0B", "#FB5607", "#FF006E", "#8338EC", "#3A86FF", "#329E32"} -- There is no max no. of colours.
colourFirst = false


reaper.Undo_BeginBlock()

inputArray = {"Marauder","Witch"}
-- the below table is used to convert plain text class names to short names.
conversionTable = {"NPCs","Marauder", "Witch", "Ranger", "Duelist", "Shadow", "Templar", "Warrior", "Sorceress", "Huntress", "Mercenary", "Monk", "Druid",      
"NPCs","Metadata/Characters/Str/StrFour", "Metadata/Characters/Int/IntFour", "Metadata/Characters/Dex/DexFour", "Metadata/Characters/StrDex/StrDexFour", "Metadata/Characters/DexInt/DexIntFour", "Metadata/Characters/StrInt/StrIntFour", "Metadata/Characters/Str/StrFourb", "Metadata/Characters/Int/IntFourb", "Metadata/Characters/Dex/DexFourb", "Metadata/Characters/StrDex/StrDexFourb", "Metadata/Characters/DexInt/DexIntFourb", "Metadata/Characters/StrInt/StrIntFourb" }

-- order of the list in the GUI.
checklistOrder = {"NPCs", "Warrior", "Witch", "Sorceress", "Ranger", "Huntress", "Mercenary", "Monk", "Druid", "Duelist", "Shadow", "Templar", "Marauder"}

-- this table gets populated on button press to a list of who can be imported.
whoToImport = {}

-- this preset are the buttons on the gui which are on by default.
preset1 = {true, false, false, false, false, false, false, false, false, false, false, false, false }

-- this version SKIPS blank cells.
function createConfigTableFromClipboard()
  clipboard = reaper.CF_GetClipboard('')
  
  configTable = {}
  -- Iterate through each line and insert it into the table
  for line in clipboard:gmatch("[^\n\t\r]*") do
      table.insert(configTable, line)
  end   
end

-- converts a plain text name, e.g., witch, into a short name, e.g., Int4.
function convertNameToShortName (input)
local result
        for n = 1, 13 do
          if input == conversionTable[n] then
          result = conversionTable[n+13]
          end
        end
return result
end

function convertShortNameToName (input)
local result
        for n = 1, 13 do
          if input == conversionTable[n+13] then
          result = conversionTable[n]
          end
        end
return result
end

-- this is the function called when the 'Import ALL' button is pressed.
function runAll()
whoToImport = {"NPCs","Metadata/Characters/Str/StrFour", "Metadata/Characters/Int/IntFour", "Metadata/Characters/Dex/DexFour", "Metadata/Characters/StrDex/StrDexFour", "Metadata/Characters/DexInt/DexIntFour", "Metadata/Characters/StrInt/StrIntFour", "Metadata/Characters/Str/StrFourb", "Metadata/Characters/Int/IntFourb", "Metadata/Characters/Dex/DexFourb", "Metadata/Characters/StrDex/StrDexFourb", "Metadata/Characters/DexInt/DexIntFourb", "Metadata/Characters/StrInt/StrIntFourb"}
createConfigTableFromClipboard()
spacing = GUI.Val("Spacing(s):")
runFunction()

reaper.Undo_EndBlock("Paste ALL from Config Editor (NPCTalkDialogueTextAudio)",-1)
end



-- this is the function called when the 'Import Selected' button is pressed.
function runSelectedOnly()
whoToImport = {}

-- the below block takes the GUI checklist and populates the whoToImport table only with enabled values.
checklistArray = GUI.Val("Who to Import")
  for i = 1, 13 do
      if checklistArray[i] == true then
        table.insert(whoToImport,convertNameToShortName(checklistOrder[i]))
      end
  end
  
createConfigTableFromClipboard()
spacing = GUI.Val("Spacing(s):")
runFunction()

reaper.Undo_EndBlock("Paste from Config Editor, Filtered (NPCTalkDialogueTextAudio)",-1)
end




--GUI 
-- Script's GUI generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please install 'Lokasenna's GUI library v2 for Lua', available on ReaPack, then run the 'Set Lokasenna_GUI v2 library path.lua' script in your Action List.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()

-- required classes to be loaded for GUI elements.
GUI.req("Classes/Class - Textbox.lua")()
GUI.req("Classes/Class - Button.lua")()
GUI.req("Classes/Class - Options.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end



GUI.name = "Import"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 128, 540
GUI.anchor, GUI.corner = "mouse", "C"

-- Import ALL button
GUI.New("Import ALL", "Button", {
    z = 11,
    x = 16,
    y = 430,
    w = 90,
    h = 45,
    caption = "Import ALL",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = runAll
})

-- Import Selected Button
GUI.New("Import Selected", "Button", {
    z = 11,
    x = 16,
    y = 375,
    w = 90,
    h = 45,
    caption = "Import Selected",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = runSelectedOnly
})

-- Checklist of Who to Import
GUI.New("Who to Import", "Checklist", {
    z = 12,
    x = 16,
    y = 26,
    w = 96,
    h = 340,
    caption = "NPCTalkDialogue\nTextAudio",
    optarray = {"NPCs", "Warrior", "Witch", "Sorceress", "Ranger", "Huntress", "Mercenary", "Monk", "Druid", "Duelist", "Shadow", "Templar", "Marauder"},
    dir = "v",
    pad = 4,
    font_a = 2,
    font_b = 3,
    col_txt = "txt",
    col_fill = "elm_fill",
    bg = "wnd_bg",
    frame = true,
    shadow = true,
    swap = nil,
    opt_size = 20
})

-- Spacing Input Field.
GUI.New("Spacing(s):", "Textbox", {
    z = 11,
    x = 75,
    y = 485,
    w = 40,
    h = 20,
    caption = "Spacing(s)",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

-- Run the GUI. Runs until the window is closed.
GUI.Init()
GUI.Main()

-- Sets the default values on the GUI.
GUI.Val("Spacing(s):", "5")
GUI.Val("Who to Import", preset1)

-- GUI SCRIPTING OVER.
-- :) 

function reduceToFileNameOnly(input)
-- removes filepath and .ogg extensions.
local extensionRemoved = (string.gsub(input, ".ogg", ""))
local fileNameOnly = string.match(extensionRemoved, "([^/]+)$")
return fileNameOnly
end

function pasteConfigAudio (path,textinput)

if textinput == nil or textinput =="" then
textinput = ""
end

local pos = reaper.GetCursorPosition()
local fullpath = dialoguePath..path
itemStartPos = reaper.GetCursorPosition()
local fixed_path = (string.gsub(fullpath, "\\\\", "/"))
reaper.InsertMedia(fixed_path, 0)
--inserts asset

local itemEndPos = reaper.GetCursorPosition()
reaper.SetEditCurPos(itemEndPos+spacing,true,false)
-- sets edit cursor to appropriate place for the NEXT asset.

local fileName = reduceToFileNameOnly(path)
reaper.AddProjectMarker2(0, false, itemStartPos, 0, fileName, -1, 0)
--adds a marker with filename for rendering.

-- pastes a text item on the same track.
local track = reaper.GetSelectedTrack(0, 0)
local item = reaper.AddMediaItemToTrack(track)
reaper.SetMediaItemInfo_Value(item, "D_POSITION", pos)
reaper.SetMediaItemInfo_Value(item, "D_LENGTH", itemEndPos-pos+spacing-1) -- Length in seconds
reaper.GetSetMediaItemInfo_String(item,"P_NOTES",textinput,true)
--text block


end







if not force_color and not reaper.CF_GetCustomColor then
  reaper.MB("SWS extension is required by this script.\nPlease download it on https://www.sws-extension.org/ or via reapack on https://www.reapack.com", "Warning", 0)
 -- return
end

function hex2rgb(HEX_COLOR) -- sourced: https://gist.github.com/jasonbradley/4357406
    local hex = HEX_COLOR:sub(2)
    return tonumber('0x'..hex:sub(1,2)), tonumber('0x'..hex:sub(3,4)), tonumber('0x'..hex:sub(5,6))
end

function NativeToHex(nativeColour)
    -- Get RGB from native COPIED
    local R = (nativeColour >> 16) & 0xFF
    local G = (nativeColour >> 8) & 0xFF
    local B = nativeColour & 0xFF
    -- Format to hex string (#RRGGBB)
    return string.format("#%02X%02X%02X", R, G, B)
end




function runFunction()

reaper.Undo_BeginBlock()

id = ""
speaker = ""
text = ""
assetList = {}
textList = {}
characterFilterPassed = false
charFilterList = {}

stepCount = (#configTable+1)/8

for i = 1, stepCount do
  assetList = {}
  textList = {}
  id = configTable[i*8-7]
  
    if (configTable[i*8-6]=="") then
              speaker = configTable[i*8-5]
            else
              speaker = configTable[i*8-6]
              -- speaker is an npc.
              -- check character filter column for whoToImport values.
              characterFilters = configTable[i*8-1]
              
              if characterFilters == nil or characterFilters == "" or #whoToImport ==1 then
                -- if there is no character filter, then all classes are fine.
              characterFilterPassed = true
              else
              
              for item in string.gmatch(characterFilters, "([^, ]+)") do
                  table.insert(charFilterList, item)
              end
              
              
              
                --  if any value is on both who to import and character filters, then pass charr filters
                for i=1, #whoToImport do
                      for a=1, #charFilterList do
                      
                        if whoToImport[i] == charFilterList[a] then
                        characterFilterPassed = true
                      end
                end
              end
              end
              
    end
  text = configTable[i*8-4]
  assets = configTable[i*8-3]
--above gets data for each step.

insertStep = false
for i = 1, #whoToImport do
if speaker == whoToImport[i] then
insertStep = true
end

-- if a non-PC is talking, insert step if NPC option is activated.
if string.sub(speaker, 1, 19) ~= "Metadata/Characters" and whoToImport[1]== "NPCs" then

      -- but only if the character being talked to would pass the character filter.
      if characterFilterPassed then
      insertStep = true
      end
end
end

--the below cancels the import if a line break (or something else) misaligns cells.
if (id == "") or (string.sub(id, 1, 4) == "4.0/") then
reaper.MB("Likely, there is a line break somewhere within the text of the final step imported: \n"..lastID.."\n :( You should be fine to continue importing from where this was cancelled.", "Import ended early!", 0)
return
end

     if insertStep == true then     
        
            reaper.SelectAllMediaItems(0,false)
            --deselectallitems
            
            local assetsFormatted = string.gsub(assets, ", ", "\n")
            for line in assetsFormatted:gmatch("[^\r\n]+") do
                table.insert(assetList, line)
            end
            -- above four lines formats asset list for inserting. PER STEP.
            
            textSplit = string.gsub(text, "<continue>", "\n")
            for line in textSplit:gmatch("[^\r\n]+") do
                table.insert(textList, line)
            end
            -- above four lines formats text for inserting. PER STEP
            
            currentPos = reaper.GetCursorPosition() 
            -- gets position before inserting anything.
            if #assetList == 0 then
              if#textList>0 then
                for i =1, #textList do
                pasteText = textList[i]
              pasteConfigAudio("NullFile/Null_3s.ogg",pasteText)
                end
                else
              pasteConfigAudio("NullFile/Null_3s.ogg","")
              end
            else
              for i = 1, #assetList do
              pasteAsset = assetList[i]
              pasteText = textList[i]
              pasteConfigAudio(pasteAsset,pasteText)
              end
            end
            --above pastes assets in a row.
            
            endPos = reaper.GetCursorPosition()
            -- gets position after the step has been inserted.
            
            -- COLOUR REGIONS TO RANDOM FOR EACH DIFFERENT NPC CONVOS.
            idNPCTag = id:match("([^_]+_[^_]+_)") 
            if lastIdNPCTag == idNPCTag then
            if colourFirst == true then
            colour = "#808080"
            end
            else
            randColour = colourscheme[math.random(1,#colourscheme-1)]
            
              if randColour == lastColour then
              colour = colourscheme[#colourscheme]
              else
              colour = randColour
              end
            end
            R,G,B = hex2rgb(colour) -- R because r is already taken by reaper, the rest is for consistency
            lastColour = colour
            
            -- saves the convo id, NOT step ID, to compare on the next inserted step.
            -- this allows colour to change when a new convo starts.
           
             _, underscorecount = string.gsub(id, "_", "_")
            if underscorecount >= 2 or underscorecount == nil then
            lastIdNPCTag = id:match("([^_]+_[^_]+_)")
            else
            lastIdNPCTag = "convoIDnotRelevant"
            end
            lastID = id
            -- END OF COLOUR STUFF
            
            reaper.AddProjectMarker2(0, true, currentPos, endPos-1, id, -1, reaper.ColorToNative(R,G,B)|0x1000000)
            --insert region with id
            
            
        end
end
end

