-- @description Paste NPCTalkDialogueTextAudio from Config Editor
-- @author ewan
-- @version 1.3
-- @changelog
--    Added filtering functionality and relevant GUI.

-- @about
--   Copy the first five columns from config and paste them into reaper.

--HOW TO:
-- COPY the first FIVE columns in config for the steps you want to paste.
-- Then, run this action at the point in the reaper session you wish to insert them.
-- Enter the number of seconds you want to separate each line.

dialoguePath = [[D:\SVN\4.0.0\bin\Client\Audio\Dialogue\]]
-- Paste your dialogue path above, if not the same as mine. 

-- The colour used is chosen at random, and is guaranteed to not be the same as the preceeding region.
-- On the below line is where you can define your colour scheme with hex codes.
colourscheme = {"#FFBE0B", "#FB5607", "#FF006E", "#8338EC", "#3A86FF", "#329E32"} -- There is no max no. of colours.
colourFirst = false


reaper.Undo_BeginBlock()

inputArray = {"Marauder","Witch"}

conversionTable = {"NPCs","Marauder", "Witch", "Ranger", "Duelist", "Shadow", "Templar", "Warrior", "Sorceress", "Huntress", "Mercenary", "Monk", "Druid",      
"NPCs","Metadata/Characters/Str/StrFour", "Metadata/Characters/Int/IntFour", "Metadata/Characters/Dex/DexFour", "Metadata/Characters/StrDex/StrDexFour", "Metadata/Characters/DexInt/DexIntFour", "Metadata/Characters/StrInt/StrIntFour", "Metadata/Characters/Str/StrFourb", "Metadata/Characters/Int/IntFourb", "Metadata/Characters/Dex/DexFourb", "Metadata/Characters/StrDex/StrDexFourb", "Metadata/Characters/DexInt/DexIntFourb", "Metadata/Characters/StrInt/StrIntFourb" }

checklistOrder = {"NPCs", "Warrior", "Witch", "Sorceress", "Ranger", "Huntress", "Mercenary", "Monk", "Druid", "Mercenary", "Shadow", "Druid", "Marauder"}

whoToImport = {}

preset1 = {true, false, false, false, false, false, false, false, false, false, false, false, false }

function createConfigTableFromClipboard()
  clipboard = reaper.CF_GetClipboard('')
  
  configTable = {}
  -- Iterate through each line and insert it into the table
  for line in clipboard:gmatch("[^\r\n\t]+") do
      table.insert(configTable, line)
  end
end

function convertNamesToShortNames (input)
convertedArray = {}
  for i = 1, #input do
      for n = 1, 13 do
          if input[i] == conversionTable[n] then
          convertedArray [i] = conversionTable[n+13]
          end
      end
  end
end

function convertNameToShortName (input)
local result
        for n = 1, 13 do
          if input == conversionTable[n] then
          result = conversionTable[n+13]
          end
        end
return result
end


function runAll()
whoToImport = {"NPCs","Metadata/Characters/Str/StrFour", "Metadata/Characters/Int/IntFour", "Metadata/Characters/Dex/DexFour", "Metadata/Characters/StrDex/StrDexFour", "Metadata/Characters/DexInt/DexIntFour", "Metadata/Characters/StrInt/StrIntFour", "Metadata/Characters/Str/StrFourb", "Metadata/Characters/Int/IntFourb", "Metadata/Characters/Dex/DexFourb", "Metadata/Characters/StrDex/StrDexFourb", "Metadata/Characters/DexInt/DexIntFourb", "Metadata/Characters/StrInt/StrIntFourb"}
createConfigTableFromClipboard()
spacing = GUI.Val("Spacing(s):")
runFunction()

reaper.Undo_EndBlock("Paste from Config Editor",-1)
end

function runSelectedOnly()
whoToImport = {}
checklistArray = GUI.Val("Who to Import")

  for i = 1, 13 do
      if checklistArray[i] == true then
        table.insert(whoToImport,convertNameToShortName(checklistOrder[i]))
      end
  end
createConfigTableFromClipboard()
spacing = GUI.Val("Spacing(s):")
runFunction()
reaper.Undo_EndBlock("Paste from Config Editor",-1)
end

--GUI 

-- Script generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please install 'Lokasenna's GUI library v2 for Lua', available on ReaPack, then run the 'Set Lokasenna_GUI v2 library path.lua' script in your Action List.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()



GUI.req("Classes/Class - Textbox.lua")()
GUI.req("Classes/Class - Button.lua")()
GUI.req("Classes/Class - Options.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end



GUI.name = "Config Import Gui"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 128, 540
GUI.anchor, GUI.corner = "mouse", "C"



GUI.New("Import ALL", "Button", {
    z = 11,
    x = 16,
    y = 416,
    w = 90,
    h = 45,
    caption = "Import ALL",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = runAll
})

GUI.New("Import Selected", "Button", {
    z = 11,
    x = 16,
    y = 356,
    w = 90,
    h = 45,
    caption = "Import Selected",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = runSelectedOnly
})




GUI.New("Who to Import", "Checklist", {
    z = 12,
    x = 16,
    y = 16,
    w = 96,
    h = 330,
    caption = "Who To Import?",
    optarray = {"NPCs", "Warrior", "Witch", "Sorceress", "Ranger", "Huntress", "Mercenary", "Monk", "Druid", "Mercenary", "Shadow", "Druid", "Marauder"},
    dir = "v",
    pad = 4,
    font_a = 2,
    font_b = 3,
    col_txt = "txt",
    col_fill = "elm_fill",
    bg = "wnd_bg",
    frame = true,
    shadow = true,
    swap = nil,
    opt_size = 20
})

GUI.New("Spacing(s):", "Textbox", {
    z = 11,
    x = 75,
    y = 480,
    w = 40,
    h = 20,
    caption = "Spacing(s)",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})


GUI.Init()
GUI.Main()


checklistArray = GUI.Val("Who to Import")
GUI.Val("Spacing(s):", "5")
GUI.Val("Who to Import", preset1)





--retval, spacing = reaper.GetUserInputs("ewan: Paste From Config (NPCTalkDialogueTextAudio)", 1, "Space between lines(s)","5")


function reduceToFileNameOnly(input)
local extensionRemoved = (string.gsub(input, ".ogg", ""))
local fileNameOnly = string.match(extensionRemoved, "([^/]+)$")
return fileNameOnly
end

function pasteConfigAudio (path,textinput)
local pos = reaper.GetCursorPosition()
local fullpath = dialoguePath..path
itemStartPos = reaper.GetCursorPosition()
local fixed_path = (string.gsub(fullpath, "\\\\", "/"))
reaper.InsertMedia(fixed_path, 0)
--inserts asset

local itemEndPos = reaper.GetCursorPosition()
reaper.SetEditCurPos(itemEndPos+spacing,true,false)

local fileName = reduceToFileNameOnly(path)
reaper.AddProjectMarker2(0, false, itemStartPos, 0, fileName, -1, 0)
--adds a marker with filename for rendering.


local track = reaper.GetSelectedTrack(0, 0)
local item = reaper.AddMediaItemToTrack(track)
reaper.SetMediaItemInfo_Value(item, "D_POSITION", pos)
reaper.SetMediaItemInfo_Value(item, "D_LENGTH", itemEndPos-pos+spacing-1) -- Length in seconds
reaper.GetSetMediaItemInfo_String(item,"P_NOTES",textinput,true)
--text block


end







if not force_color and not reaper.CF_GetCustomColor then
  reaper.MB("SWS extension is required by this script.\nPlease download it on https://www.sws-extension.org/ or via reapack on https://www.reapack.com", "Warning", 0)
 -- return
end

function hex2rgb(HEX_COLOR) -- sourced: https://gist.github.com/jasonbradley/4357406
    local hex = HEX_COLOR:sub(2)
    return tonumber('0x'..hex:sub(1,2)), tonumber('0x'..hex:sub(3,4)), tonumber('0x'..hex:sub(5,6))
end

function NativeToHex(nativeColour)
    -- Get RGB from native COPIED
    local R = (nativeColour >> 16) & 0xFF
    local G = (nativeColour >> 8) & 0xFF
    local B = nativeColour & 0xFF
    -- Format to hex string (#RRGGBB)
    return string.format("#%02X%02X%02X", R, G, B)
end




function runFunction()

reaper.Undo_BeginBlock()

id = ""
speaker = ""
text = ""
assetList = {}
textList = {}

stepCount = #configTable/4

for i = 1, stepCount do
  assetList = {}
  textList = {}
  id = configTable[i*4-3]
  speaker = configTable[i*4-2]
  text = configTable[i*4-1]
  assets = configTable[i*4]
--above gets data for each step.

insertStep = false
for i = 1, #whoToImport do
if speaker == whoToImport[i] then
insertStep = true
end
if string.sub(speaker, 1, 19) ~= "Metadata/Characters" and whoToImport[1]== "NPCs" then
insertStep = true
end
end


     if insertStep == true then     
        
            reaper.SelectAllMediaItems(0,false)
            --deselectallitems
            
            assetsFormatted = string.gsub(assets, ", ", "\n")
            for line in assetsFormatted:gmatch("[^\r\n]+") do
                table.insert(assetList, line)
            end
            -- above four lines formats assets for inserting.
            
            textSplit = string.gsub(text, "<continue>", "\n")
            for line in textSplit:gmatch("[^\r\n]+") do
                table.insert(textList, line)
            end
            -- above four lines formats text for inserting.
            
            currentPos = reaper.GetCursorPosition()
            
            for i = 1, #assetList do
            pasteAsset = assetList[i]
            pasteText = textList[i]
            pasteConfigAudio(pasteAsset,pasteText)
            end
            --above pastes assets in a row.
            
            endPos = reaper.GetCursorPosition()
            --reaper.SetEditCurPos(endPos+30,true,false)
            --above moves the cursor forwards before next assets are pasted.
            
            --insert an item below with the text on it
            
            
            -- COLOUR REGIONS TO RANDOM FOR EACH DIFFERENT NPC CONVOS.
            idNPCTag = id:match("([^_]+_[^_]+_)") 
            if lastIdNPCTag == idNPCTag then
            if colourFirst == true then
            colour = "#808080"
            end
            else
            randColour = colourscheme[math.random(1,#colourscheme-1)]
            
              if randColour == lastColour then
              colour = colourscheme[#colourscheme]
              else
              colour = randColour
              end
            end
            R,G,B = hex2rgb(colour) -- R because r is already taken by reaper, the rest is for consistency
            lastColour = colour
            
            reaper.AddProjectMarker2(0, true, currentPos, endPos-1, id, -1, reaper.ColorToNative(R,G,B)|0x1000000)
            --insert region with id
            
            lastIdNPCTag = id:match("([^_]+_[^_]+_)")
            -- END OF COLOUR THEORY. ba dum chhh
        end
end
end




