-- @description Delete Markers or Regions in Time Selection or in Area Encompassed by Selected Items
-- @author ewan
-- @version 1
-- @about
--   Use GUI to Delete Markers or Regions in Time Selection or in Area Encompassed by Selected Items


local r = reaper

function removeMarkersRegionsInTimeBounds(t_start,t_end,m_type)
local delrgn = false
local delmarker = false
if m_type == "regionOnly" then
delrgn = true
end
if m_type == "markerOnly" then
delmarker = true
end
if m_type == "both" then
delrgn = true
delmarker = true
end

local i = 0
while true do
  local retval, isrgn, pos, rgnend, name, markrgnindexnumber, color = reaper.EnumProjectMarkers(i)
  -- this exits the loop if there are no more markers or regions to evaluate.
    if retval == 0 then
    --keepRunning = 0
    break
    end
    
  -- If its a region, check if it needs deleting, if not skip to the next region.
    if isrgn == true then
    -- if we are focussed on a region then
        if delrgn == true then
                if (pos >= t_start and pos < t_end) or (pos < t_start and rgnend >= t_start) then
                -- check if the region overlaps time sel, and if yes, delete it.
                  reaper.DeleteProjectMarkerByIndex(0,i)
                else
                -- If region is not in the time selection, we skip to the next.
                i = i + 1
                end
          else
          i = i + 1
          end
    else
    -- if its a marker, skip to the next.
        if delmarker == true then
                if (pos >= t_start and pos < t_end) or (pos < t_start and rgnend >= t_start) then
                -- check if the marker overlaps time sel, and if yes, delete it.
                  reaper.DeleteProjectMarkerByIndex(0,i)
                else
                -- If region is not in the time selection, we skip to the next.
                i = i + 1
                end
            else
            i = i + 1
            end
    end
  end -- end of while loop
end -- end of function

function getTimeSelAndItems ()
local timestart, timeend = reaper.GetSet_LoopTimeRange2(0, false, false, 0, 0, false)
  for i = 0, reaper.CountSelectedMediaItems()-1 do
    local selectedItem = reaper.GetSelectedMediaItem(activeProjectIndex, i)
    local selectedItemPosition = reaper.GetMediaItemInfo_Value(selectedItem, "D_POSITION")
    local selectedItemLength = reaper.GetMediaItemInfo_Value(selectedItem, "D_LENGTH")
      if selectedItemPosition < timestart then
      timestart = selectedItemPosition
      end
      if selectedItemPosition + selectedItemLength > timeend then
      timeend = selectedItemPosition + selectedItemLength
      end

  end
return timestart, timeend
end


function removeBoth()
reaper.Undo_BeginBlock()
timeStart, timeEnd = getTimeSelAndItems()
removeMarkersRegionsInTimeBounds(timeStart,timeEnd,"both")
reaper.Undo_EndBlock("Removed Regions and Markers in Time Sel. or Area Encompassed by Sel. Items.",-1)
end

function removeMarkersOnly()
reaper.Undo_BeginBlock()
timeStart, timeEnd = getTimeSelAndItems()
removeMarkersRegionsInTimeBounds(timeStart,timeEnd,"markerOnly")
reaper.Undo_EndBlock("Removed Markers in Time Sel. or Area Encompassed by Sel. Items.",-1)
end

function removeRegionsOnly()
reaper.Undo_BeginBlock()
timeStart, timeEnd = getTimeSelAndItems()
removeMarkersRegionsInTimeBounds(timeStart,timeEnd,"regionOnly")
reaper.Undo_EndBlock("Removed Regions in Time Sel. or Area Encompassed by Sel. Items.",-1)
end

-- GUI
-- Script generated by Lokasenna's GUI Builder

local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please install 'Lokasenna's GUI library v2 for Lua', available on ReaPack, then run the 'Set Lokasenna_GUI v2 library path.lua' script in your Action List.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()


GUI.req("Classes/Class - Button.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end

GUI.name = "Click to Remove"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 178, 54
GUI.anchor, GUI.corner = "mouse", "C"

GUI.New("Regions", "Button", {
    z = 11,
    x = 64,
    y = 10,
    w = 50,
    h = 24,
    caption = "Regions",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = removeRegionsOnly
})

GUI.New("Markers", "Button", {
    z = 11,
    x = 7,
    y = 10,
    w = 50,
    h = 24,
    caption = "Markers",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = removeMarkersOnly
})

GUI.New("Both", "Button", {
    z = 11,
    x = 121,
    y = 10,
    w = 50,
    h = 24,
    caption = "Both",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = removeBoth
})

GUI.Init()
GUI.Main()

